version: "3.8"
services:
  backend:
    container_name: backend
    image: mztnnrt/go-local:latest
    restart: always
    environment:
      DEBUG_MODE: true
    ports:
      - 8080:8080
      - 2345:2345
    working_dir: /go/src/backend
    volumes:
      - ./backend:/go/src/backend
